name: task_manager
description: A collaborative task management application built with Flutter following Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Utils
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Testing
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  hive_test: ^1.0.1
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true